// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunningStats.Data;

#nullable disable

namespace RunningStats.Migrations
{
    [DbContext(typeof(RunningStatsContext))]
    [Migration("20231222182141_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RunningStats.Models.RunningModel", b =>
                {
                    b.Property<int>("RunningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunningId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<decimal>("Meters")
                        .HasColumnType("numeric(5)");

                    b.Property<decimal>("Minutes")
                        .HasColumnType("numeric(4)");

                    b.HasKey("RunningId");

                    b.ToTable("RunningModel");
                });
#pragma warning restore 612, 618
        }
    }
}
